baseURL = 'https://eme-ce.github.io/'
locale = 'latam'
title = 'bLogging'
theme = 'minimal-black'

[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 8

[[menus.main]]
  name = 'About'
  pageRef = '/about'
  weight = 16

[[menus.main]]
  name = 'Blog'
  pageRef = '/posts'
  weight = 24
